// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yqogsdbzdeqckajtowvt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlxb2dzZGJ6ZGVxY2thanRvd3Z0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk1ODIwNDQsImV4cCI6MjA1NTE1ODA0NH0.3_XsJqKz6kJf5RRSRB5Ur66o23HSN0iLr3y9xxn-FGE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);